spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8181/realms/fitness-oauth2/protocol/openid-connect/certs}
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:lb://USER-SERVICE}
          predicates:
            - Path=/api/users/**
        - id: activity-service
          uri: ${ACTIVITY_SERVICE_URL:lb://ACTIVITY-SERVICE}
          predicates:
            - Path=/api/activities/**
        - id: ai-service
          uri: ${AI_SERVICE_URL:lb://AI-SERVICE}
          predicates:
            - Path=/api/recommendations/**
server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/